# tomcat 配置
server:
  port: 9092
  servlet:
    context-path: /home-customer

spring:
  application:
    name: home-customer

# eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
