# tomcat 端口
server:
  port: 9091

# 服务名称
spring:
  application:
    name: zuul-gateway

# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/

# zuul网关配置
zuul:
  prefix: /teacherblitz
  routes:
    customer:
      path: /home-customer/**
      serviceId: home-customer
      strip-prefix: false
    feign:
      path: /home-feign/**
      serviceId: home-feign
      strip-prefix: false

